GET http://localhost:3700/players/

#####
GET http://localhost:3700/players/8/
 
#####
 
PUT  http://localhost:3700/players/8/
Content-Type: application/json

{
  "playerName": "Raju"
}
######
 
GET http://localhost:3700/matches/18/
 
#####
GET  http://localhost:3700/matches/10/players